version: '3.9'

services:
  mongo:  # CHANGÉ: "mongo" au lieu de "mongodb"
    image: mongo:7.0
    container_name: blog-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: blogdb
    ports:
      - "27011:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: blog-mongo-ui
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo  # CHANGÉ: correspond au nom du service
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH: 'false'
    ports:
      - "8088:8081"
    depends_on:
      - mongo  # CHANGÉ: correspond au nom du service

volumes:
  mongo_data: